-- Library7 Supabase setup
-- Run this in Supabase SQL Editor.
-- This creates the database tables, enables RLS, and creates a media bucket.
-- For a private library, the example policies below require signed-in users.
-- If you want public read access, adjust the SELECT policies carefully.

create extension if not exists pgcrypto;

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  author text,
  description text,
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.people (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.loans (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books(id) on delete cascade,
  person_id uuid not null references public.people(id) on delete cascade,
  created_at timestamptz not null default now(),
  returned_at timestamptz
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('loan','return')),
  book_id uuid references public.books(id) on delete set null,
  person_id uuid references public.people(id) on delete set null,
  book_title text not null,
  person_name text not null,
  created_at timestamptz not null default now()
);

alter table public.books enable row level security;
alter table public.people enable row level security;
alter table public.loans enable row level security;
alter table public.activity enable row level security;

-- Authenticated users can manage the library.
create policy "library authenticated books" on public.books for all to authenticated using (true) with check (true);
create policy "library authenticated people" on public.people for all to authenticated using (true) with check (true);
create policy "library authenticated loans" on public.loans for all to authenticated using (true) with check (true);
create policy "library authenticated activity" on public.activity for all to authenticated using (true) with check (true);

-- Storage bucket for photos. Create it in Dashboard if this insert is unavailable.
insert into storage.buckets (id, name, public)
values ('library-media','library-media',true)
on conflict (id) do nothing;

create policy "library media authenticated read" on storage.objects
for select to authenticated using (bucket_id = 'library-media');

create policy "library media authenticated upload" on storage.objects
for insert to authenticated with check (bucket_id = 'library-media');

create policy "library media authenticated update" on storage.objects
for update to authenticated using (bucket_id = 'library-media') with check (bucket_id = 'library-media');

create policy "library media authenticated delete" on storage.objects
for delete to authenticated using (bucket_id = 'library-media');

-- Helpful constraint: at most one active loan per book.
create unique index if not exists one_active_loan_per_book
on public.loans(book_id) where returned_at is null;
